# Generated by Django 6.0.3 on 2026-04-01 10:44

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=200)),
                ('categoryImage', models.ImageField(upload_to='images/Category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategoryName', models.CharField(max_length=200)),
                ('subCategoryImage', models.ImageField(upload_to='images/SubCategory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ElearningApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonName', models.CharField(max_length=200)),
                ('lessonDescription', ckeditor_uploader.fields.RichTextUploadingField()),
                ('lessonImage', models.ImageField(upload_to='images/Lesson')),
                ('lessonDate', models.DateTimeField(auto_now_add=True)),
                ('lessonPdf', models.FileField(blank=True, null=True, upload_to='pdfs/lessons/')),
                ('categoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='ElearningApp.category')),
                ('subCategoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='ElearningApp.subcategory')),
            ],
        ),
    ]
