# Generated by Django 6.0.3 on 2026-04-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElearningApp', '0002_contactmessage_alter_lesson_categoryid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogoName', models.CharField(max_length=200)),
                ('TopDescription', models.CharField(max_length=200)),
                ('BodyTop', models.CharField(max_length=150)),
                ('BodyMid', models.CharField(max_length=150)),
                ('BodyBottom', models.CharField(max_length=200)),
                ('ImageBody', models.ImageField(upload_to='image/Hero')),
            ],
        ),
    ]
